//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoComunidad
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdministracionComunidadEntities : DbContext
    {
        public AdministracionComunidadEntities()
            : base("name=AdministracionComunidadEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Partidas> Partidas { get; set; }
        public DbSet<Propietarios> Propietarios { get; set; }
        public DbSet<Propios> Propios { get; set; }
        public DbSet<Usantes> Usantes { get; set; }
    }
}
