//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoComunidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comunidades
    {
        public decimal numerador { get; set; }
        public string nombrecomunidad { get; set; }
        public string nif { get; set; }
        public string direcion { get; set; }
        public string cp { get; set; }
        public string localidad { get; set; }
        public string provincia { get; set; }
        public string mail { get; set; }
        public string telefono1 { get; set; }
        public string telefono2 { get; set; }
        public string iban1 { get; set; }
        public string iban2 { get; set; }
        public string iban3 { get; set; }
        public string iban4 { get; set; }
        public string iban5 { get; set; }
        public string iban6 { get; set; }
        public Nullable<decimal> presupuesto { get; set; }
        public Nullable<bool> porcoeficiente { get; set; }
        public Nullable<bool> porcuotafija { get; set; }
        public Nullable<decimal> cuotamensual { get; set; }
        public Nullable<decimal> saldoinicial { get; set; }
        public Nullable<decimal> agua { get; set; }
        public Nullable<decimal> electricidad { get; set; }
        public Nullable<decimal> telefonia { get; set; }
        public Nullable<decimal> reparaciones { get; set; }
        public Nullable<decimal> indemnizaciones { get; set; }
        public Nullable<decimal> limpieza { get; set; }
        public Nullable<decimal> ascensor { get; set; }
        public Nullable<decimal> extintores { get; set; }
        public Nullable<decimal> jardines { get; set; }
        public Nullable<decimal> otros { get; set; }
        public Nullable<decimal> compras { get; set; }
        public Nullable<decimal> gestoria { get; set; }
        public Nullable<decimal> letrados { get; set; }
        public Nullable<decimal> sueldos { get; set; }
        public Nullable<decimal> segsocial { get; set; }
        public Nullable<decimal> seguros { get; set; }
        public Nullable<decimal> gastosfinancieros { get; set; }
        public Nullable<decimal> numeropropietarios { get; set; }
        public Nullable<bool> activa { get; set; }
    }
}
