//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoComunidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Propietarios
    {
        public decimal numerador { get; set; }
        public string nombre { get; set; }
        public string comunidad { get; set; }
        public string nif { get; set; }
        public string direcion { get; set; }
        public string localidad { get; set; }
        public string provincia { get; set; }
        public string cp { get; set; }
        public Nullable<System.DateTime> fechaalta { get; set; }
        public string profesion { get; set; }
        public string telefono1 { get; set; }
        public string telefono2 { get; set; }
        public string cargo { get; set; }
        public string mail { get; set; }
        public Nullable<bool> piso { get; set; }
        public string numpiso { get; set; }
        public Nullable<decimal> coefpiso { get; set; }
        public Nullable<bool> local { get; set; }
        public string numlocal { get; set; }
        public Nullable<decimal> coeflocal { get; set; }
        public Nullable<bool> garaje { get; set; }
        public string numgaraje { get; set; }
        public Nullable<decimal> coefgaraje { get; set; }
        public Nullable<bool> trastero { get; set; }
        public string numtrastero { get; set; }
        public Nullable<decimal> coeftrastero { get; set; }
        public string iban1 { get; set; }
        public string iban2 { get; set; }
        public string iban3 { get; set; }
        public string iban4 { get; set; }
        public string iban5 { get; set; }
        public string iban6 { get; set; }
        public string observaciones { get; set; }
    }
}
