//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoComunidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usantes
    {
        public decimal numerador { get; set; }
        public string nombre { get; set; }
        public string password { get; set; }
        public string pregunta { get; set; }
        public string respuesta { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<decimal> cod { get; set; }
        public string nivel { get; set; }
    }
}
