//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Propios
    {
        public decimal numerador { get; set; }
        public string minombre { get; set; }
        public string micif { get; set; }
        public string midirecion { get; set; }
        public string mipoblacion { get; set; }
        public string miprovincia { get; set; }
        public string micp { get; set; }
        public string mitelef1 { get; set; }
        public string mitelef2 { get; set; }
        public string mifax { get; set; }
        public string micontacto { get; set; }
        public string mimail { get; set; }
        public string miiban1 { get; set; }
        public string miiban2 { get; set; }
        public string miiban3 { get; set; }
        public string miiban4 { get; set; }
        public string miiban5 { get; set; }
        public string miiban6 { get; set; }
        public string milogo { get; set; }
        public string miidentificadorbancario { get; set; }
        public string mibic { get; set; }
    }
}
